# Generated by Django 4.1.7 on 2023-02-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50, verbose_name='Enter First Name')),
                ('LastName', models.CharField(max_length=50, verbose_name='Enter Last Name')),
                ('City', models.CharField(max_length=50, verbose_name='Enter City')),
            ],
        ),
    ]
